version: "3"

services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postmangovkh_dev
    ports:
      - "5432:5432"
    volumes:
      - pg-data1:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - "6379:6379"
volumes:
  pg-data1: