version: "3"

services:
  postgres:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nomsagovkh_dev
    ports:
      - "5432:5432"
    volumes:
      - pg-data-nomsa1:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    container_name: redis-nomsa
    ports:
      - "6379:6379" 
  maildev:
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --verbose
    environment:
      - MAILDEV_OUTGOING_USER=admin
      - MAILDEV_OUTGOING_PASS=123 
    ports:
      - "1080:80"
      - "1025:25"
volumes:
  pg-data-nomsa1: